import type { HTMLAttributes, ReactNode } from 'react'
import { AlertCircle, Inbox, LoaderCircle } from 'lucide-react'
import { cn } from '../../lib/utils'
import { Card, CardBody } from '../ui/Card'
import { Button } from '../ui/Button'

export function BusinessPage({ className, ...props }: HTMLAttributes<HTMLElement>) { return <main className={cn('mx-auto w-full max-w-[1500px] space-y-5 px-4 py-5 sm:px-6 sm:py-6 lg:px-8', className)} {...props} /> }
export function PageHeader({ title, subtitle, actions }: { title: ReactNode; subtitle?: ReactNode; actions?: ReactNode }) { return <header className="flex min-h-12 flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div className="min-w-0"><h1 className="text-2xl font-semibold tracking-tight text-foreground">{title}</h1>{subtitle && <p className="mt-1 max-w-3xl text-sm leading-5 text-muted-foreground">{subtitle}</p>}</div>{actions && <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>}</header> }
export function FilterSurface({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('flex flex-wrap items-center gap-2', className)}>{children}</div> }
export function SectionHeading({ title, description, actions }: { title: ReactNode; description?: ReactNode; actions?: ReactNode }) { return <div className="flex min-w-0 items-start justify-between gap-4"><div className="min-w-0"><h2 className="text-[15px] font-semibold tracking-tight text-foreground">{title}</h2>{description && <p className="mt-1 text-sm leading-5 text-muted-foreground">{description}</p>}</div>{actions && <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>}</div> }
export function MetricCard({ label, value, supportingText, tone = 'neutral', onClick }: { label: string; value: ReactNode; supportingText?: string; tone?: 'neutral' | 'info' | 'success' | 'warning' | 'critical'; onClick?: () => void }) { const color = { neutral:'bg-muted-foreground', info:'bg-info', success:'bg-success', warning:'bg-warning', critical:'bg-critical' }[tone]; const content=<CardBody className="min-h-[108px] p-5 text-left"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-muted-foreground">{label}</p><span className={cn('size-2 rounded-full',color)} /></div><p className="mt-2 text-2xl font-semibold tracking-tight tabular-nums">{value}</p>{supportingText && <p className="mt-1 text-xs text-muted-foreground">{supportingText}</p>}</CardBody>; return <Card className={cn('min-h-[108px]',onClick&&'cursor-pointer transition-shadow hover:shadow-md')}>{onClick?<Button variant="ghost" className="block h-full w-full rounded-lg p-0 text-left hover:bg-transparent" onClick={onClick}>{content}</Button>:content}</Card> }
export function LoadingState({ text='正在加载数据…' }: { text?: string }) { return <div className="flex min-h-40 flex-col items-center justify-center gap-2 text-sm text-muted-foreground" role="status"><LoaderCircle className="size-5 animate-spin" />{text}</div> }
export function EmptyState({ title='暂无数据', description, action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="flex min-h-44 flex-col items-center justify-center px-5 text-center"><span className="mb-3 grid size-10 place-items-center rounded-full bg-muted"><Inbox className="size-5 text-muted-foreground" /></span><p className="font-medium">{title}</p>{description&&<p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p>}{action&&<div className="mt-4">{action}</div>}</div> }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="flex min-h-40 flex-col items-center justify-center gap-3 px-5 text-center" role="alert"><AlertCircle className="size-6 text-critical" /><div><p className="font-medium">内容暂时无法加载</p><p className="mt-1 text-sm text-muted-foreground">{message}</p></div>{onRetry&&<Button variant="outline" size="sm" onClick={onRetry}>重新加载</Button>}</div> }
